### ISSUE TITLE
Bug: Fix "last edited by" information

### ISSUE THREAD

**Issue by 501st-alpha1** [oponder/big-gollum#13]
Currently, the Git commits generated by the software are assigned the info of the user running the server. (And if that user doesn't have Git configured, the name is set to Anonymous.) I'm going to try to get it to use the info of the logged-in user.

**Comment by oponder** [comment]
Hey Scott,

I'm adding you to the collaborators list for this repo. If you feel confident about things you can move them along without me being a bottleneck.

No official procedure or rules at the moment. 

However I'd like to still review code in pull requests if you want me to, and I'd also like for you to review my code if you'd like and have the time for it. So my plan is that I'll be making pull requests too for new features, and you can merge them in or leave your :+1:

**Comment by 501st-alpha1** [comment]
Cool, thanks! That review process sounds good to me. :+1:
