### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by 501st-alpha1** [oponder/big-gollum#2]
Is this project still active? It seems to have some of the functionality I am looking for, so I'd like to contribute to it if so.

Also, I'd like recommend that you [choose a license](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license). I'd rather not contribute to this until I know that it is actually open-source (or better, free) software.

**Comment by oponder** [comment]
Hey Scott,

Thanks for the pull request! I haven't looked at this project in a long time. Did you manage to get it running?

I havent played around with this in a while. Will set up a easy license and go from there. I like the idea of the project too, so maybe we can make something of it? I have some free time.

Any tips for the license I should use? I would like it to be free and open for anyone to use.

Regards!

**Comment by 501st-alpha1** [comment]
Glad to hear you are still around. Yes, after applying the fix in my PR, I got it up and running without problems.

As mentioned, I'm definitely willing to help out as much as time allows. Do you have any specific plans for what you will be working on? I'll try to coordinate to avoid any duplication of work, haha.

The choice of license will mainly depend on whether you any derivatives of this project to be free / open source software (i.e. whether you want the project to be copyleft). That is what I generally do, and for that I recommend the [GNU GPL](https://gnu.org/licenses/gpl.html). Otherwise, if you want it to be ["copycenter"](http://catb.org/~esr/jargon/html/C/copycenter.html), then the [Apache](http://www.apache.org/licenses/LICENSE-2.0.html) and [MIT](http://opensource.org/licenses/MIT) licenses seem to be the most common, though I haven't look into them in as much detail.

**Comment by oponder** [comment]
I think the first things I will do is upgrade to rails 4 and do a bit of general clean up on the way.

The way gollum is integrated is kind of nasty. Now that I've had a couple more years of development experience I might be able to improve on that.

Realistically, I think i will only be able to do those two things the weekend after next weekend. (11th and 12th). If you're itching to get started be my guest. 

I'll probably have no trouble carrying your new features over, as long as they aren't too complex. I'm seeing mostly nice usability things on being able to edit the wiki after it has been made, nice stuff!

Then it would be a nice codebase to continue adding interface features on, like you are already doing.

I'm quite interested in the deploying part of things, so after that I could focus on making it runnable on heroku / docker or something so interested people can play around with it quickly.

**Comment by 501st-alpha1** [comment]
Cool, sounds great to me!

**Comment by oponder** [comment]
Closing this issue. 

The project is officially still active. I wanna keep it small and cute and will track my progress here #3
