### ISSUE TITLE
Is this a single port solution?

### ISSUE THREAD

**Issue by hoijui** [oponder/big-gollum#30]
Does this support multiple wikis run on a single port, or does it run one gollum instance per repo, using one port each?

**Comment by 501st-alpha1** [comment]
Yes, multiple wikis run behind a single Big Gollum instance, and in fact you can create new wikis from the UI.

On the backend, Gollum is linked as a Ruby adapter, so we aren't starting a entirely new instance every time, and thus there aren't any extra ports being used.

It does still count as one Gollum instance per wiki, so each wiki will have its own Git repo.

**Comment by hoijui** [comment]
niiiice, thank you! :-)

**Comment by 501st-alpha1** [comment]
No problem!
