### ISSUE TITLE
Task: Add tests for the creating / editing / and destroying of wikis.

### ISSUE THREAD

**Issue by oponder** [oponder/big-gollum#8]

**Comment by 501st-alpha1** [comment]
I'd like to volunteer to work on this one.

Should we also be testing that the relevant files/folders under `/wikis` are being created/edited/deleted correctly?

**Comment by oponder** [comment]
Yeah, I'm not totally sure how to approach that! I'm still learning and internalising testing practices.

I think you can unit test wiki_initializer in lib/wiki_initializer.rb, (so there you could check that it creates the folder)

Curious to see what you come up with and learning from your approach too! Go for it!

**Comment by 501st-alpha1** [comment]
I've started work on this. I'm using Cucumber and Rspec, since it looks like you had started using those already.

**Comment by oponder** [comment]
:+1:
